export PATH="/home/wfarris/bin:$PATH"
export EDITOR="nvim"
export VISUAL="nvim"
alias vim="nvim"
alias se="cd /home/wfarris/configurations && nvim shell.zsh"
alias code="/mnt/c/Program\ Files/Microsoft\ VS\ Code/bin/code"
